Feature/te5 t625 android web services
buddhdev-jay/Android_Demo_Kotlin pull request #14
Opened 2022-03-17 04:42 UTC by buddhdev-jay

2022-04-04 03:44 UTC, Purvesh-Dodiya requested changes

2022-04-04 03:44 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/android_demo_kotlin/WebServices/LoginActivity.kt
> +        val prefs = getSharedPreferences("sharedPrefLogin", Context.MODE_PRIVATE)
static key "sharedPrefLogin"

2022-04-04 03:44 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/android_demo_kotlin/WebServices/LoginActivity.kt
> +                                editor.putBoolean("lockedState", isLogged)
static key

2022-04-04 03:44 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/android_demo_kotlin/WebServices/LoginActivity.kt
> +
extra empty line

2022-04-04 03:44 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/android_demo_kotlin/adapter/RecyclerviewApiAdapter.kt
> +
code formatting

2022-04-05 04:46 UTC, Purvesh-Dodiya requested changes

2022-04-05 04:46 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/android_demo_kotlin/WebServices/LoginActivity.kt
> +
extra empty line

2022-04-05 04:46 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/android_demo_kotlin/WebServices/LoginActivity.kt
> +                                editor.putBoolean("lockedState", isLogged)
pending

2022-04-05 06:26 UTC, purvesh-d requested changes

2022-04-05 06:26 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/WebServices/RecyclerWebActivity.kt
> +            val url = URL(BASE_URL + "api/users?page=2")
Check in whole file for static keys and move to constant

2022-04-05 06:26 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/WebServices/LoginActivity.kt
> +            if (responseCode == 200) {
static number, check in whole file

2022-04-05 06:26 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/WebServices/LoginActivity.kt
> +            } else if (responseCode == 400) {
same

2022-04-05 08:08 UTC, purvesh-d requested changes

2022-04-05 08:08 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/adapter/RecyclerviewApiAdapter.kt
> +                    firstNameOfUser.text = usersList[position].firstName
use apply for `usersList[position]`

2022-04-05 13:34 UTC, purvesh-d approved these changes

2022-04-05 13:34 UTC, merged