TE5-T422 ExpandableListview Done
buddhdev-jay/Android_Demo_Kotlin pull request #8
Opened 2022-02-24 06:21 UTC by buddhdev-jay

2022-02-24 10:49 UTC, purvesh-d requested changes

2022-02-24 10:49 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/GridLayoutRecyclerViewActivity.kt
> +        val layoutManager = GridLayoutManager(this, 2)
static number

2022-02-24 10:49 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/MainActivity.kt
> +        }
code formatting

2022-02-24 10:49 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/adapter/ExpandableListviewAdapter.kt
> +
empty line

2022-02-24 10:49 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/adapter/ExpandableRecyclerAdapter.kt
> +            nameTxt.text = AppList[position].namehello
use `with` or `apply` for 
`nameTxt.text = AppList[position].namehello
dateTxt.text = AppList[position].date
apiTxt.text = AppList[position].apilevel
descriptionTxt.text = AppList[position].description`

2022-02-24 10:49 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/adapter/ExpandableRecyclerAdapter.kt
> +
empty line

2022-02-24 10:49 UTC, purvesh-d commented on app/src/main/res/layout/item_recyclerview_expandable.xml
> +    <LinearLayout
Why Linear layout used?

2022-02-24 11:59 UTC, purvesh-d requested changes

2022-02-24 11:59 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/GridLayoutRecyclerViewActivity.kt
> +        recylerview_grid.addItemDecoration(dividerItemDecoration)
use apply

2022-02-24 11:59 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/adapter/ExpandableRecyclerAdapter.kt
> +                val version = AppList[position]
version var is requierd?

2022-02-24 11:59 UTC, purvesh-d commented on app/src/main/res/layout/item_recyclerview_expandable.xml
> +
extra empty line

2022-02-25 04:34 UTC, purvesh-d requested changes

2022-02-25 04:34 UTC, purvesh-d commented on app/src/main/java/com/example/android_demo_kotlin/GridLayoutRecyclerViewActivity.kt
> +    var recycler_adapter: RecyclerviewGridAdapter? = null
variable name should be in camel case

2022-02-25 04:35 UTC, buddhdev-jay commented on app/src/main/java/com/example/android_demo_kotlin/GridLayoutRecyclerViewActivity.kt
> +    var recycler_adapter: RecyclerviewGridAdapter? = null
ok i will change

2022-02-25 04:39 UTC, merged